version: "3.7"
services:
  healthapi-db:
    image: mysql:5.7
    volumes:
      - healthapi_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: healthapi
      MYSQL_USER: me
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
volumes:
  healthapi_db:
